# Generated by Django 5.2 on 2026-06-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auditlog_allowed_radius_auditlog_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_radius',
            field=models.PositiveIntegerField(default=100, help_text='Allowed radius in meters'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='require_location',
            field=models.BooleanField(default=False, help_text='Require location verification'),
        ),
    ]
