# Generated by Django 5.2 on 2026-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_allowed_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='allowed_radius',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='require_location',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Optional: Google Meet/Zoom/Teams link'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('physical', '🏢 Physical (In-Person with Location)'), ('online', '💻 Online (Virtual - Code Only)')], default='physical', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='require_location',
            field=models.BooleanField(default=False, help_text='Require GPS verification for physical classes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
